# Generated by Django 2.1.5 on 2019-02-01 15:32

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='open', max_length=10)),
                ('destination', models.CharField(max_length=50)),
                ('arrivaldate', models.DateTimeField()),
                ('passenger', models.IntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)])),
                ('sharable', models.BooleanField(default=False)),
                ('vehicle', models.CharField(blank=True, max_length=20)),
                ('special', models.CharField(blank=True, max_length=200)),
                ('driver_id', models.IntegerField(blank=True, default=-1)),
                ('rider_id', models.IntegerField(default=-1)),
                ('sharer_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=users.models.emptylist, size=None)),
                ('sharer_passenger', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=users.models.emptylist, size=None)),
                ('total_psg', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.BooleanField(default=False)),
                ('vehicle', models.CharField(blank=True, max_length=20)),
                ('plate', models.CharField(blank=True, max_length=10)),
                ('capacity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)])),
                ('special', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
